services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: always
    networks:
      - public_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/ready"]
      interval: 10s # Tempo entre as checagens
      timeout: 5s # Tempo limite para o comando responder
      retries: 3 # Quantas vezes pode falhar antes de marcar como 'unhealthy'
      start_period: 5s # Tempo de carência para a aplicação iniciar antes de começar a valer

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      prometheus:
        condition: service_healthy
    restart: always
    networks:
      - public_network
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  http-simulator:
    image: pierrevincent/prom-http-simulator:0.1
    ports:
      - "8080:8080"
    restart: always
    networks:
      - public_network
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge
